// <auto-generated />
using System;
using AbpDemo.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbpDemo.Migrations
{
    [DbContext(typeof(AbpDemoDbContext))]
    [Migration("20190928030701_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbpDemo.SysFileInfos.FileInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Extension")
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .HasMaxLength(300);

                    b.Property<DateTime>("LastAccessTime");

                    b.Property<DateTime>("LastWriteTime");

                    b.Property<long>("Length");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("SHA1")
                        .HasMaxLength(50);

                    b.Property<TimeSpan>("TimeSpan");

                    b.HasKey("Id");

                    b.ToTable("FileInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
